./runDHTBucketsAgressive.sh 2>&1 | tee dht_buckets_agressive.txt
./runDHTBucketsKindergarten.sh 2>&1 | tee dht_buckets_kindergarten.txt
./runDHTBucketsKarma.sh 2>&1 | tee dht_buckets_karma.txt
./runDHTBucketsPolka.sh 2>&1 | tee dht_buckets_polka.txt
./runDHTBucketsPolite.sh 2>&1 | tee dht_buckets_polite.txt
./runDHTBucketsPassive.sh 2>&1 | tee dht_buckets_passive.txt
./runDHTBucketsLess.sh 2>&1 | tee dht_buckets_less.txt
./runDHTBucketsTimestamp.sh 2>&1 | tee dht_buckets_timestamp.txt
#./runDHTLocksTests.sh 2>&1 | tee dht_locks.txt
